### ISSUE TITLE
Boolean value gets cut from the end of query

### ISSUE THREAD

**Issue by vladshcherbin** [scriptcoded/sql-highlight#10]
👋 Hey, I've got a query:

```sql
select "users".* from "users" where "email" = 'test@gmail.com' and "is_banned" = true
```

Boolean value gets cut, I've tried both `false` and `true` as values:

![image](https://user-images.githubusercontent.com/6711845/82254423-7a3b4600-995b-11ea-810d-f35b268b02a2.png)

3.2.0

**Comment by scriptcoded** [comment]
Hey! This has been lingering for a while... @ggerhard came in with some fixes that makes this a non-problem in #12 :)
