### ISSUE TITLE
Timestamps break query

### ISSUE THREAD

**Issue by vladshcherbin** [scriptcoded/sql-highlight#11]
When using timestamps in query, highlighted query is broken. Query:

```sql
insert into "user_tokens" ("created_at", "token", "updated_at", "user_id") values ('2020-05-19T07:18:54.434Z', 'zQiYVIFKXHC0YPZ-HsGo4_8nta9WuV', '2020-05-19T07:18:54.434Z', 1) returning "id"
```

Result:

![image](https://user-images.githubusercontent.com/6711845/82296908-96ba9b00-99ba-11ea-8b5f-2d360fa3505e.png)

**Comment by scriptcoded** [comment]
Hey! This has been lingering for a while... @ggerhard came in with some fixes that makes this a non-problem in #12 :) It's released with version 3.3.0
