### ISSUE TITLE
[Suggestion] Don't include bots in list of contributors

### ISSUE THREAD

**Issue by parallels999** [scriptcoded/sql-highlight#140]
In it the CONTRIBUTORS section lists, the `dependabot[bot]`, `semantic-release-bot`, `github-actions[bot]`, `scriptsbot` bots are as  contributors. I think bots shouldn't be included in the list. Let me know what you think.

**Comment by scriptcoded** [comment]
Hey! Are you talking about the contributors list on the right hand side of the README? If so, I can't control this list, GitHub does that. It's a verbatim list of all users who have committed to the repo. And my little bots are contributing quite a lot :)

![image](https://github.com/scriptcoded/sql-highlight/assets/6452991/62cf15ed-d48c-4271-a28f-0c68f8ff3a51)

**Comment by parallels999** [comment]
Setting private activities on bots, I have seen that other packages hide them
I really don't know how they do it
