### ISSUE TITLE
Bug on backslashes

### ISSUE THREAD

**Issue by parallels999** [scriptcoded/sql-highlight#153]
**Describe the bug**

I add this on `debug.js`
```js
console.log(highlight('SELECT \'\\ \r \t \n \' AS text;'))
```

So i expect:
```sql
SELECT '\\ \r \t \n ' AS text;
```
Bu i get:
```sql
SELECT '\    
' AS text;
```

I don't know if it only happens to me or if some extra configuration must be done for it to work in this case, I have a text area that allows line breaks and special characters

**Comment by scriptcoded** [comment]
Hi! This is actually just how JavaScript behaves and has nothing to do with what the library does. For example if you do `console.log('Hello\nWorld')` you would expect the output to be
```
Hello
World
```
not
```
Hello\nWorld
```


So this is just an issue with how the output is being displayed. So either escape your result (by replacing `\n` with `\\n` or something like that) or make sure your input is escaped.
