### ISSUE TITLE
Any non-keyword word is considered as identifier

### ISSUE THREAD

**Issue by vladshcherbin** [scriptcoded/sql-highlight#189]
**Describe the bug**

```sql
insert into "brands" ("name") values ('Aston Martin') returning "id", "name"
```

In this example `returning` keyword is not in keywords list and is considered as `identifier`.

**Expected behavior**
Any non-keyword should be considered `unknown` or all keywords should be added to the keywords list.

All keywords can be taken from [postgres docs](https://www.postgresql.org/docs/current/sql-keywords-appendix.html#KEYWORDS-TABLE)

**Screenshots**

<img width="653" alt="image" src="https://github.com/scriptcoded/sql-highlight/assets/6711845/355a14e1-2eeb-48dc-b464-6903a8523d66">

**sql-highlight (please complete the following information):**

 - Version: 5.0.0-beta.2

**Comment by Qtax** [comment]
This is also an issue for any non-postgres SQL dialect that has more/some other keywords.

**Comment by wkeese** [comment]
> Any non-keyword should be considered unknown

If we did that though, then **no** strings would be marked as identifiers. 

>  or all keywords should be added to the keywords list... All keywords can be taken from [postgres docs](https://www.postgresql.org/docs/current/sql-keywords-appendix.html#KEYWORDS-TABLE)

I guess that's a better argument, although I cringe to think that in a string like below, "a" and "c" would be marked as keywords rather than identifiers:

> select * from tab where a > c

The current architecture (doing everything by regexp) has inherent limitations, so there need to be some compromises.  It seems like adding all those strings as keywords might make things worse (overall) rather than better.

**Comment by wkeese** [comment]
PS: I guess what I'm saying is that it's only safe to list reserved keywords in the keywords section (and "returning" is non-reserved).

**Comment by scriptcoded** [comment]
Hey there. I think to avoid the odd cases such as `a > c` we'll just keep accepting suggestions for new keywords for the time being. The `returning` keyword was added in #188 so I'll mark this as closed.

**Comment by kodi** [comment]
Another question,

I am running into problems, with 
```sql
insert into "schema"."tbl_name"...
```
where schema.tbl_name will be considered string instead of identifier.
you can see the same thing happening here with `"brands"`

**Comment by wkeese** [comment]
@kodi - I think that's just how it works; the whole architecture is based on regexps so there's no way to differentiate between the two strings in this example:

```
select * from "emp" where name = "Bill"
```

Actually I'm surprised you can quote schema or table names at all.  Can you quote column names too?  Given a command like below, how could a database know that "name" is a column but "Bill" is a literal string?

```
select * from "emp where "name" = "Bill"
```
