### ISSUE TITLE
Four highlight issues, minor

### ISSUE THREAD

**Issue by reiniiriarios** [scriptcoded/sql-highlight#19]
**Describe the bug**

- Strings seem to not be highlighted correctly if the word _not_ is present; untested with other keywords
- END seems to be missing a highlight
- != is missing a highlight on the !
- ( has the wrong highlight when next to SELECT

**Screenshots**
![image](https://user-images.githubusercontent.com/80431903/113432521-841b3b80-93ab-11eb-8897-74fd1356e55e.png)

Thanks! Super useful tool.

**Comment by scriptcoded** [comment]
Thanks for reporting this. I'm really sorry I haven't been able to check on it yet. I'll let this sit for now - if someone has a good solution, be my guest to open a PR :)

**Comment by scriptcoded** [comment]
Hey! These issues should now have been resolved in version 3.3.4. If the issues persist, feel free to leave a comment here and I'll reopen the issue.

Cheers!
