### ISSUE TITLE
OVERLAPS word is not highlighted

### ISSUE THREAD

**Issue by vladshcherbin** [scriptcoded/sql-highlight#26]
**Describe the bug**

`overlaps` word is not highlighted (used in postgres)

**To Reproduce**

Test query:

```sql
SELECT "huddles".* FROM "huddles" INNER JOIN "huddle_guests" ON "huddles"."id" = "huddle_guests"."huddle_id" WHERE "huddle_guests"."user_id" IN (2) AND "huddles"."cancelled_at" IS NULL AND ("start_date", "end_date") OVERLAPS ('2021-08-21 08:50:00.000', '2021-08-21 09:35:00.000')
```

**Expected behavior**

Should be highlighted same as `keyword`.

**Screenshots**

![image](https://user-images.githubusercontent.com/6711845/130315420-2ec3519b-39e8-437c-93eb-ac85a6551574.png)

**Versions**

**sql-highlight**: 4.0.0
**node**: 16.0.0

**Comment by scriptcoded** [comment]
Yup, sounds like a fair point. I'll merge your PR right away. Thanks!

**Comment by vladshcherbin** [comment]
@scriptcoded thank you ❤️
