### ISSUE TITLE
Breaks when using double quotes in query

### ISSUE THREAD

**Issue by vladshcherbin** [scriptcoded/sql-highlight#4]
👋 

Hey, I've got a simple query:

```sql
SELECT "users".* FROM "users"
```

It's not properly highlighted and is even cut in console output:

![image](https://user-images.githubusercontent.com/6711845/79717333-06693780-82e2-11ea-84e1-40c2d9067ed1.png)

v3.0.0

**Comment by scriptcoded** [comment]
This was a slight overlook from my part. I've added double quotes to the string matcher in [v3.1.0](https://www.npmjs.com/package/sql-highlight/v/3.1.0).

**Comment by vladshcherbin** [comment]
@scriptcoded perfect, thanks, works correct now 🎉
