### ISSUE TITLE
BUG: Syntax highlighting stopped after the period separator in `DATABASE`.`TABLENAME` syntax.

### ISSUE THREAD

**Issue by tfrancois** [scriptcoded/sql-highlight#60]
With the latest release, syntax formatting failed immediately after the period in the first occurrence of the  `DATABASE`.`TABLENAME` in my SQL code where I was performing a DROP statement prior to a CREATE PROCEDURE

See below for example:

![image](https://user-images.githubusercontent.com/5649433/184558404-f5319817-80ab-4b2d-9664-96786b1a9dac.png)

Hopefully this issue can be identified and resolved quickly -thank you.

UPDATE: To confirm, the issue does not appear with version @4.1.1 of the library.

**Comment by scriptcoded** [comment]
Thanks for reporting this!

There was a gap in our tests that allowed us to introduce this bug in the last release. I've made a fix and it should be available in https://github.com/scriptcoded/sql-highlight/releases/tag/v4.2.1. Please have a look and make sure everything works as expected! :)

**Comment by tfrancois** [comment]
Works perfect!  Thank you for the quick response.
