### ISSUE TITLE
Add human-readable color alias

### ISSUE THREAD

**Issue by vladshcherbin** [scriptcoded/sql-highlight#7]
👋 

Hey, it would be nice if it was possible to define colors like `blue`, `magenta`, etc as addition to `\x1b[34m` and similar.

It removes the need to find what codes are used for colors for unprepared developer and gives easy way to define human-readable colors. Even a table with colors can be added in docs to show, what colors are available.

What do you think?

**Comment by scriptcoded** [comment]
I could see this being implemented rather easily. I'm having one concern though. Just providing colors as strings could work, but providing some form of enum would make more sense in my opinion:

```javascript
const highlighted = highlight(query, {
  {
    keyword: colors.GREEN,
    ...
  }
})
```

For this to work the enum must be exported by the library somehow, which in turn means having named exports. This directly interferes with #5 and specifically 80bb46617704e87c2d4cfa54ccb7ecd8dab1a486, which includes a deprecation warning for using named exports.

I think this actually speaks for removing the default export all together, as having a single way of using the library seems more clear all together.

**Comment by vladshcherbin** [comment]
I'm actually not a fan of this constants, I'd rather use `'blue'` instead of `colors.BLUE` for simplicity and minimalism.

**Comment by scriptcoded** [comment]
@vladshcherbin I totally see that using a string is more straight forward and probably makes the code a bit cleaner. What I don't want however, is to disrupt alternate usages for this library. Now, albeit being a very clear edge case, this library could be used to add any prefix to parts of an SQL query. Specifying `keyword: '[keyword]'` would work perfectly fine (I think) and produce something like `[keyword]SELECT * [keyword]FROM test`. You could also do `keyword: 'green'`, and although that might seem like a stretch, I don't want to prevent it. I'd rather be explicit than potentially be in the way for other developers.

**Comment by vladshcherbin** [comment]
@scriptcoded hm, maybe I'm missing something or misunderstood: won't a check for color work?

e.g.
1) if color is `blue`. Check if `blue` exists in default colors, yes it does -> take its code and set `[blue color code]SELECT`
2) if color is `y67`. Check if `y67` exists in default colors, nope -> use it as it is and set `[y67]SELECT`

**Comment by vladshcherbin** [comment]
Oh, you probably mean actual word `blue` as user set so it won't be changed to `[blue color code]`. That makes sense now, even if it sounds like an edge case, maybe someone will need it :)

**Comment by erikn69** [comment]
https://gist.github.com/abritinthebay/d80eb99b2726c83feb0d97eab95206c4

**Comment by scriptcoded** [comment]
Hey. This issue has been open for quite a while without a resolution. I think adding a map of color codes doesn't add much value as these codes are already easy to find on the internet. There is also no way to include the full range of 24 bit color codes which are technically possible to use too. Anyways, I've included a link to a page with some basic color codes in the readme which will hopefully help novice developers with customizing the highlighting.
