### ISSUE TITLE
Add possibility to set highlighter casing

### ISSUE THREAD

**Issue by vladshcherbin** [scriptcoded/sql-highlight#9]
👋 

Hey, it's me again. I believe this is the last feature I miss.

It would be useful to be able to set casing for highlighters. This is useful when you have query in lowercase and want to set some parts of it (e.g. keywords) to uppercase.

Opening this one because currently there is `color` option, however highlighters can have other features later, for example `order`, `casing`, `bgColor`, `mode` (bold, dim), etc. This needs a little thinking forward to some advanced config:

```js
highlight(query, {
  highlighters: {
    keyword: { color: 'blue', casing: 'uppercase' },
    number: { mode: 'bold, color: 'magenta' }
  }
})
```

Maybe something similar to example above or other syntax, but needs to be considered since it's related to my previous issues (https://github.com/scriptcoded/sql-highlight/issues/6, https://github.com/scriptcoded/sql-highlight/issues/7)

**Comment by scriptcoded** [comment]
Hey, thanks for the input, and sorry for leaving you hanging for such a long while!

While I understand your use case, I feel like that is outside the scope of the library. I want to keep the library as plain and straight forward as possible, and I think adding text transformations takes away from that point. We're only dealing with colors. 

Background color and mode can already be specified using the options, although the current API might not being very intuitive for novice users. Perhaps that a basis for another issue.
